apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
  - name: debug
    image: curlimages/curl:8.2.1  # صورة جاهزة مع curl
    command: ["sleep", "infinity"]

